global:
  edition: ce

  hosts:
    domain: local
    https: false
    gitlab:
      name: gitlab.local

  ingress:
    configureCertmanager: false

  # Optional: if you create a custom StorageClass for GitLab PVs
  # See storage.yaml below
  # gitlab:
  #   rails:
  #     persistentVolume:
  #       storageClass: gitlab-storage

nginx-ingress:
  enabled: false

certmanager:
  install: false

prometheus:
  install: false

redis:
  install: true

postgresql:
  install: true

gitlab:
  webservice:
    service:
      type: NodePort
      nodePort: 32080    # HTTP on VM's node
  gitlab-shell:
    service:
      type: NodePort
      nodePort: 32222    # SSH (optional)

registry:
  enabled: false         # Save some resources for this lab
