apiVersion: v1
kind: Service
metadata:
  name: iot-app
  labels:
    app: iot-app
spec:
  type: ClusterIP
  selector:
    app: iot-app
  ports:
    - name: http
      port: 8888
      targetPort: 8888
